### PR TITLE
Add /count method to models that returns just metadata

### PR DESCRIPTION
**Pull request by dark12222000**
### Does this resolve an issue?
#47 - Adds in /count which gives desired response and supports full query capabilities

### Description of changes proposed in this pull request
Gives back metadata such as totalCount, totalPages and limit. Internally runs count() directly without a find().

### Who should review this pull request?
@mingard - Original Issue
@jimlambie

### Testing
```
curl -X GET -H "Authorization: Bearer d91cd13b-b7d5-4e9f-8e93-64f977e418e2" -H "Content-Type: application/json" -H "Cache-Control: no-cache" "http://localhost:3000/vtest/testdb/test-schema/count"
```

### Sample Response
```
{
  "metadata": {
    "limit": 40,
    "totalCount": 0,
    "totalPages": 0
  }
}
```

### CODE REVIEW

**Comment by dark12222000** [comment]
@jimlambie - I attempted to match style within file as closely as possible but if you have a project preference for style just let me know and I'll update

**Comment by eduardoboucas** [comment]
Can I just ask why the need for an additional endpoint? Couldn't the endpoint currently used to query a collection be adapted to just deliver metadata, either by an additional query parameter (`format=metadata`?) or even by using the existing `fields` — if the request actively says it doesn't want any fields, we deliver just the `metadata` block. I appreciate `/count` is internally running a `count()` instead of a `find()`, but I see no reason why the existing endpoint couldn't handle that special case.

It means there isn't an additional endpoint to maintain, document and keep track of, and any consumers downstream (such as [API wrapper](https://github.com/dadi/api-wrapper)) don't have to implement it.

Unless I'm missing something obvious, in which case please ignore. 😅

**Comment by dark12222000** [comment]
Internally the existing model level find() is > 100 lines, and the count method has around 40 lines of difference, so they're split. There's a lot of potential for them to diverge in the future, and even right now they support some different options.

This is a big enough change that I think it's worth documenting and intentionally implementing. It's also not a mandatory or breaking change - downstream can take their time to implement as they see fit. 

I'd hate to sell count/find as the same thing only for them to diverge farther in the future which would really mess with downstream.

**Comment by eduardoboucas** [comment]
How do you see them diverging? I think the opposite actually. If the existing endpoint delivers `results` and `metadata` and the new one returns just `metadata`, I would expect both `metadata` object to always be the same. I want to be able to consume this object regardless of whether I need to display any actual documents or not. In my view, keeping these two under the same endpoint would be the best way of guaranteeing consistency in the future.

> I'd hate to sell count/find as the same thing only for them to diverge farther in the future which would really mess with downstream.

Unless @mingard has something different in mind, I think his feature request was just that — a way of obtaining the same metadata we currently get from querying a collection, but without having to transfer the actual documents across the wire. In my view, it's an optimisation to an existing feature/endpoint.

If later down the road we decided to add more metadata to this `/count` endpoint, wouldn't we want to make sure a normal query contains that data as well? Why wouldn't you want to do that? And if that's the case, you're now in a situation where you need to build functionality in two separate endpoints.

**Comment by mingard** [comment]
@eduardoboucas is right - this does not satisfy the requirement elegantly. It's an unnecessary edition. All we need is the ability to flag that all we require from
The query is the metadata block. Seems simple enough

**Comment by mingard** [comment]
Either `results=false` or `metadata=true` work for me. The first suggest the removal of results and the second suggests only metadata, however the second may cause issues if we require the ability to remove metadata. Having said that, I can see no logic that would require the removal of metadata

**Comment by jimlambie** [comment]
@mingard @eduardoboucas @dark12222000 

Valid points from all of you. However, in defence of the approach taken, the original issue could've specified the requirement with the detail you're now supplying. In fact, it suggests:

> an additional /meta endpoint, give the ability to get meta-like detail with filters e.g.
http://host.com:80/1.0/db/collection/metadata?filter={"answer": "yes"}

With API issues piling up, someone took the initiative and submitted a PR containing a solution that matched the requirement.

**Comment by mingard** [comment]
@jimlambie The points @eduardoboucas makes is that there is a better and more elegant way, to which I agree. I don't disagree that the original request contained suggestions that could be improved on. That's why we discuss these things.

**Pull request merged**
