### PR TITLE
Use @dadi/boot module to standardise startup text

### PR DESCRIPTION
**Pull request by jimlambie**
To view, start the app

### CODE REVIEW

**Comment by eduardoboucas** [comment]
Just a note: [this line](https://github.com/dadi/boot/blob/master/index.js#L75) means that if you're running a version of API that is more recent than the one published in NPM, it incorrectly tells you that a newer version exists.

```sh
ℹ A newer version of @dadi/api is available: 2.2.5
```

It can be annoying for people testing nightly/beta versions of the product.

**Comment by jimlambie** [comment]
@eduardoboucas how would the message read? What it's saying really is that the latest "public" version is 2.2.5. So yeah, I agree that if you're running a beta version or from the develop branch then you're going to see the above.

Thoughts on how to word it? Maybe something like `You're running version "x.x.x", the latest public release is "x.y.z". How about an upgrade?!` .... but then only if semver-compare says the latest public version is greater than the one you are running...

**Comment by eduardoboucas** [comment]
My idea was: if the version you’re running is *lower* than the one published on NPM, we display the message exactly how it is. Otherwise, we don’t display anything.

I think the wording is fine, it’s just that the comparison in the check is not strict enough (`!==` becomes `<=`). 

Does that make sense?

**Comment by jimlambie** [comment]
Sure does! 🛌

**Comment by jimlambie** [comment]
https://github.com/dadi/boot/pull/4

**Comment by eduardoboucas** [comment]
🍹

**Pull request merged**
